apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    app: cart
    tier: app
    project: roboshop
    
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: cart
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        app: cart
        tier: app
        project: roboshop
    spec:
      containers:
      - name: cart
        image: {{ .Values.deployment.imageURL }}:{{ .Values.deployment.imageVersion }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: cart
        


    
