kind: Service
apiVersion: v1
metadata:
  name: cart
  namespace: roboshop
spec:
  selector: # labels are used as selectors
    app: cart
    tier: app
    project: roboshop
      
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080