apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels: { app: rabbitmq, project: roboshop, tier: db }
spec:
  selector: { app: rabbitmq, project: roboshop, tier: db }
  ports:
    - { name: amqp, protocol: TCP, port: 5672,  targetPort: 5672 }
    - { name: mgmt, protocol: TCP, port: 15672, targetPort: 15672 }
